apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tsh-ai
  namespace: tsh
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - lechai.garry-ai.cloud
      secretName: lechai-tls
  rules:
    - host: lechai.garry-ai.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tsh-ai
                port:
                  number: 80
