apiVersion: v1
kind: Service
metadata:
  name: tsh-ai
  namespace: tsh
  labels:
    app: tsh-ai
spec:
  selector:
    app: tsh-ai
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
